[package]
name = "persistence-interface"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.sqlx]
version = "0.8.2"
[dependencies.serde]
version = "1.0.215"
features = ["derive"]
